server:
    port: 8081
spring:
    application:
        name: courier-management
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
    datasource:
        url: jdbc:postgresql://localhost:5435/courierdb
        username: postgres
        password: postgres