spring:
    application:
        name: delivery-tracking
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5435/deliverydb
        username: postgres
        password: postgres